node {
    stage('Checkout'){
            checkout scm
    }
    stage('Job DSL'){
        def template = northstar.getSeedJobDSL('seed/jobs/**/repoList.yaml');
        jobDsl scriptText: template // Run Job DSL
    }
}
