apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: default
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.319.1-lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 50
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 200
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 6Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: example
      targets: "seed/jobs/example/**/*.groovy"
      description: "Example Pipelines Repository"
      repositoryBranch: main
      repositoryUrl: https://github.com/jontaylor-nable/jenkins-local-pipelines.git
      pollSCM: "*/1 * * * *"
    - id: terraform
      targets: "seed/jobs/terraform/*.groovy"
      description: "Example TF Repository"
      repositoryBranch: main
      repositoryUrl: https://github.com/jontaylor-nable/jenkins-local-pipelines.git
      pollSCM: "*/1 * * * *"
    - id: terraform3
      targets: "seed/jobs/terraform/*.groovy"
      description: "Example TF Repository"
      repositoryBranch: main
      repositoryUrl: https://github.com/jontaylor-nable/jenkins-local-pipelines.git
      pollSCM: "*/1 * * * *"
